version: "3.8"

services:
    mysql:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql-opencart
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_USER: opencart
            MYSQL_PASSWORD: opencart
        volumes: 
            - ./docker/mysql:/var/lib/mysql
        networks:
            - opencart-network
        ports: 
            - "3307:3306"

    sso:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql-sso
        restart: always
        environment:
            MYSQL_USER: sso
            MYSQL_PASSWORD: sso
            MYSQL_TCP_PORT: 3308
            MYSQL_ROOT_PASSWORD: 1234
        volumes: 
            - ./docker/sso:/var/lib/mysql
            # - ./my.cnf:/etc/mysql/my.cnf
        networks:
            - opencart-network
        ports: 
            - "3308:3308"

    php:
        build:
            dockerfile: php.dockerfile
            context: ./docker/
        container_name: php-opencart
        volumes:
            - ./:/html
            - ./docker/logs/xdebug:/logs/xdebug
            - ./docker/config/php/custom.conf:/usr/local/etc/php-fpm.d/zz-custom.conf
            - ./docker/config/php/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini
            - ./docker/logs/php-fpm/:/tmp/xdebug_log
        depends_on: 
            - mysql
            - sso
        networks:
            - opencart-network

    nginx:
        image: nginx:latest
        container_name: nginx-opencart
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/html
            - ./docker/logs/nginx:/logs/nginx
            - ./docker/config/nginx/xdebug:/etc/nginx/xdebug
            - ./docker/config/nginx/hosts:/etc/nginx/hosts
            - ./docker/config/nginx/init.conf:/etc/nginx/conf.d/default.conf
        networks:
            - opencart-network
        depends_on: 
            - php
            - sso

networks:
    opencart-network:
        name: opencart
        driver: bridge
